### PR TITLE
[CI] Add CI builds against C-Ruby 2.4, 2.5 and 2.6

### PR DESCRIPTION
**Pull request by sfgeorge**
Test to ensure passing builds against C-Ruby 2.4, 2.5 and 2.6.

### CODE REVIEW

**Comment by bklang** [comment]
Really interesting how it passes on 2.4 and 2.6, but not 2.5.  I even re-ran the job and it still failed.  Not sure what to do about that right now - perhaps mark 2.5 as optional? Unless you want to try tackling a fix?

**Comment by sfgeorge** [comment]
@bklang Good question, yeah I found that puzzling as well.  I may temporarily add on the latest table of 2.5... _just_ to check if this is something weird about `2.5.0`.  And failing that, then I may take a couple of [milli]seconds to see if this very weird output issue is resolvable; and if that fails, I agree making 2.5 optional is a good call.

Really pleased how this works on 2.6 and 2.7.0dev though!!! 💪

**Comment by sfgeorge** [comment]
@bklang Ready for re-reviewski! 🕺

**Comment by bklang** [comment]
LGTM! :shipit:

**Review by bklang — APPROVED** [review]

**Pull request merged**
