### PR TITLE
Install pcap spec dependency

### PR DESCRIPTION
**Pull request by bklang**
And upgrade test suite to cover Ruby 2.2 & 2.3

### CODE REVIEW

**Comment by bklang** [comment]
@benlangfeld Any thoughts on how to address this? The problem is that some gems in our dependency chain (and not even our direct dependents) require `Ruby >= 2.3`.  Options:
- Officially drop support for `Ruby < 2.3`
- Specify older versions of the gems which work with older Rubies

**Comment by leifmadsen** [comment]
Just make dep >= 2.3.0

**Comment by bklang** [comment]
@lpradovera This will make Travis happy, and should unblock #92

**Comment by leifmadsen** [comment]
@bklang @benlangfeld I think this line needs to be bumped to a later version of rspec?

https://github.com/mojolingo/sippy_cup/blob/develop/sippy_cup.gemspec#L27

From what I'm Googling, we need rspec > 3.4.4

**Comment by leifmadsen** [comment]
*bump* :)

**Pull request merged**
